[MintEdition]
solana = 60
polygon = 25

[Mint]
solana = 60
polygon = 25

[CreateDrop]
solana = 40
polygon = 40

[RetryMint]
solana = 0
polygon = 0

[TransferAsset]
solana = 10
polygon = 10

[CreateWallet]
solana = 10
polygon = 10

[RetryDrop]
solana = 0
polygon = 0

[CreateCollection]
solana = 40
polygon = 0

[MintCompressed]
solana = 1
polygon = 0

[RetryCollection]
solana = 0
polygon = 0

[UpdateMint]
solana = 0
polygon = 0