version: '3.8'
services:
  db:
    image: postgres:15.1
    container_name: db
    env_file:
      - .env
    ports:
      - 5439:5432
    volumes: 
      - holaplex_hub_nfts:/var/lib/postgresql/data
volumes:
  holaplex_hub_nfts:
    driver: local