[toolchain]
channel = "nightly-2022-12-11"
components = [
  "cargo",
  "clippy",
  "rust-analysis",
  "rust-analyzer-preview",
  "rust-docs",
  "rust-src",
  "rust-std",
  "rustc",
  "rustfmt",
]
profile = "minimal"

# vim:set ft=toml:
