//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "metadata_json_uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub uri: String,
    pub identifier: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::metadata_jsons::Entity",
        from = "Column::Id",
        to = "super::metadata_jsons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MetadataJsons,
}

impl Related<super::metadata_jsons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MetadataJsons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
