//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::{entity::prelude::*, Set};

use super::sea_orm_active_enums::Blockchain;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project_wallets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project_id: Uuid,
    pub wallet_address: String,
    pub blockchain: Blockchain,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {
    /// Will be triggered before insert / update
    fn before_save(mut self, _insert: bool) -> Result<Self, DbErr> {
        if self.wallet_address.as_ref().starts_with("0x") {
            self.wallet_address = Set(self.wallet_address.as_ref().to_lowercase());
        }

        Ok(self)
    }
}
