[registry]
# endpoint = "https://schemas.holaplex.tools"
endpoint = "http://localhost:8081"

[schemas]
organization = 1
nfts = 1
customer = 1
treasury = 1
solana_nfts = 1
polygon_nfts = 1
timestamp = 1

# organization = 5
# nfts = 19
# customer = 2
# treasury = 17
# solana_nfts = 4
# polygon_nfts = 6
# timestamp = 1
