name: Merge Docker Manifests and deploy to kubes
on:
  push:
    branches:
      - main
      - release

env:
  SERVICE_NAME: nfts
  DOCKERHUB_REPO: ${{ vars.DOCKERHUB_ORG }}/${{ github.event.repository.name }}
  DOCKERHUB_MIGRATIONS_REPO: ${{ vars.DOCKERHUB_ORG }}/${{ github.event.repository.name }}-migrations
  CHECK_INTERVAL: 10

jobs:
  merge:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Wait for release workflow to succeed (arm64)
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: release (arm64)
          repo-token: ${{ secrets.ACTIONS_TOKEN }}
          wait-interval: ${{ env.CHECK_INTERVAL }}
          allowed-conclusions: success

      - name: Wait for release workflow to succeed (amd64)
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: release (amd64)
          repo-token: ${{ secrets.ACTIONS_TOKEN }}
          wait-interval: ${{ env.CHECK_INTERVAL }}
          allowed-conclusions: success

      - name: Merge image tags
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: ${{ env.DOCKERHUB_REPO }}:latest,${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          images: ${{ env.DOCKERHUB_REPO }}:latest-amd64,${{ env.DOCKERHUB_REPO }}:latest-arm64
          push: true

      - name: Merge migrations image tags
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: ${{ env.DOCKERHUB_MIGRATIONS_REPO }}:latest,${{ env.DOCKERHUB_MIGRATIONS_REPO }}:${{ github.sha }}
          images: ${{ env.DOCKERHUB_MIGRATIONS_REPO }}:latest-amd64,${{ env.DOCKERHUB_MIGRATIONS_REPO }}:latest-arm64
          push: true
      
      - name: Invoke workflow in hub-kubes repo for stage
        if: github.ref == 'refs/heads/main'
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: main
          token: ${{ secrets.ACTIONS_TOKEN }}
          workflow: release.yml
          repo: holaplex/hub-kubes
          inputs: '{ "service": "${{ env.SERVICE_NAME }}", "environment": "stage", "commit_hash": "${{ github.sha }}"}'

      - name: Invoke workflow in hub-kubes repo for prod
        if: github.ref == 'refs/heads/release'
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: main
          token: ${{ secrets.ACTIONS_TOKEN }}
          workflow: release.yml
          repo: holaplex/hub-kubes
          inputs: '{ "service": "${{ env.SERVICE_NAME }}", "environment": "prod", "commit_hash": "${{ github.sha }}"}'
